#!/usr/bin/env bash

if [ -d ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST ]
then
    echo ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST exists
    exit
fi

BRANCH=optimize

git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-Atom.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-Atom && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-ETL.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-ETL && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-Logon.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-Logon && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-Config.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-Config && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-Cluster.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-Cluster && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-Events.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-Events && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-ManagedSystems-LogicalPartitions.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-ManagedSystems-LogicalPartitions && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-ManagedSystems-VirtualIOServers.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-ManagedSystems-VirtualIOServers && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-ManagedSystems.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-ManagedSystems && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-ManagementConsole.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-ManagementConsole && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-PowerEnterprisePool.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-PowerEnterprisePool && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST-SystemTemplate.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST-SystemTemplate && \
git clone -b ${BRANCH} https://github.com/markldevine/raku-Hypervisor-IBM-POWER-HMC-REST.git ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST
ls -1d ~/github.com/raku-Hypervisor-IBM-POWER-HMC-REST*
